services:
  api:
    build: 
      context: ./api
    container_name: k8s_api
    ports:
      - "8000:8000"
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
