apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-test
  template:
    metadata:
      labels:
        app: kubernetes-test
    spec:
      containers:
      - name: kubernetes-test
        image: josefkliment/k8s-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
