apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-service
spec:
  type: NodePort
  selector:
    app: kubernetes-test
  ports:
    - protocol: TCP
      port: 8000       # port, na kterém služba běží uvnitř clusteru
      targetPort: 8000 # port v kontejneru (odpovídá containerPort)
