name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build API image
      run: |
        docker build -t josefkliment/api:latest -t ghcr.io/klimejo22/api:latest ./api

    - name: Push API image
      run: |
        docker push josefkliment/api:latest
        docker push ghcr.io/klimejo22/api:latest

    - name: Build Frontend image
      run: |
        docker build -t josefkliment/frontend:latest -t ghcr.io/klimejo22/frontend:latest ./nginx

    - name: Push Frontend image
      run: |
        docker push josefkliment/frontend:latest
        docker push ghcr.io/klimejo22/frontend:latest
